# ruff.toml
line-length = 120
target-version = "py312"

[lint]
select = ["E", "F", "W", "I", "Q", "ANN", "N", "TID", "D"]

ignore = [
    "E203",
    "D107",
    "D100",
    "D104",
    "D415",
    "D400",
    "D212",
    "D205",
    "D211",
    "D203",
    "N818",
    "ANN401",
    "ANN204"
]

[lint.per-file-ignores]
"test_*.py" = [
    "S101",    # asserts allowed in tests...
    "ARG",     # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT",     # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
    "D",
    "ANN"
]
"core/data/error_pages_data.py" = ["E501"] # Line too long due to long error message strings
"conftest.py" = ["ANN"]
"tests/conftest.py" = ["ANN"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true